image: mcr.microsoft.com/dotnet/sdk:8.0

stages:
  - build
  - deploy

variables:
  IMAGE_NAME: "tugrulhan/vocapoint-backend"
  TAG: "latest"

build:
  stage: build
  before_script:
    - dotnet restore
  script:
    - dotnet build
    - echo "build işlemi gerçekleşti"
    

deploy:
  stage: deploy
  before_script: 
    - cd WebApi
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - cd $CI_PROJECT_DIR
    - docker build -t $IMAGE_NAME:$TAG .
    - docker push $IMAGE_NAME:$TAG
