image: mcr.microsoft.com/dotnet/sdk:8.0 

stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

variables:
  IMAGE_NAME: "tugrulhan/vocapoint-backend"
  TAG: "latest"

before_script:
    - "dotnet restore"

build:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - "dotnet build"
    - echo "build işlemi gerçekleşti"
   
deploy:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  image: docker:latest
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - cd $CI_PROJECT_DIR
    - docker build -t $IMAGE_NAME:$TAG
    - docker push $IMAGE_NAME:$TAG